-- VERITAS-Vault Idempotent Cloud Schema Bootstrap v3.2
-- Enforces Zero-Trust least privilege, RLS on all tables, and strict service_role access.
begin;

-- 1. Enrolled Users
create table if not exists public.enrolled_users (
  user_id text primary key,
  name text not null,
  role text not null,
  clearance_level text default 'L3',
  image_url text default '',
  status text not null default 'APPROVED',
  created_at timestamptz default now(),
  synced_at timestamptz default now(),
  pwa_data jsonb
);

-- 2. Trusted Capture Devices
create table if not exists public.trusted_devices (
  device_id text primary key,
  checkpoint_id text not null,
  public_key text not null,
  status text not null default 'ACTIVE',
  registered_at timestamptz default now(),
  last_seen_at timestamptz
);

-- 3. Capture Sessions (Single-use challenges)
create table if not exists public.capture_sessions (
  session_id uuid primary key,
  device_id text references public.trusted_devices(device_id),
  checkpoint_id text not null,
  capture_nonce text unique not null,
  created_at timestamptz default now(),
  expires_at timestamptz not null,
  used boolean default false
);

-- 4. Privileged Maker-Checker Enrollment Requests
create table if not exists public.enrollment_requests (
  request_id uuid primary key,
  user_id text not null,
  name text not null,
  role text not null,
  clearance_level text default 'L3',
  created_by text not null,
  created_at timestamptz default now(),
  status text not null default 'PENDING',
  approved_by text,
  approved_at timestamptz,
  rejection_reason text,
  revoked_by text,
  revoked_at timestamptz,
  template_data text not null
);

-- 5. Access Audit Ledger (Hash Chained + Ed25519 Signed)
create table if not exists public.access_audit_logs (
  id bigint generated by default as identity primary key,
  event_id uuid unique,
  sequence_number bigint,
  timestamp timestamptz default now(),
  mode text not null,
  verified_parties text not null,
  party_ids text default '',
  verdict text not null,
  reason text default '',
  reason_code text default '',
  risk_score integer default 0,
  sha256_hash text not null,
  previous_hash text default '',
  event_hash text default '',
  signature text default '',
  signer_key_id text default '',
  encrypted_path text default '',
  status text default 'CLOUD_STORED',
  pwa_data jsonb
);

create index if not exists vault_audit_timestamp on public.access_audit_logs(timestamp desc);
create index if not exists vault_audit_seq on public.access_audit_logs(sequence_number);

-- 6. Vault State Records (CAS)
create table if not exists public.vault_records (
  id text primary key,
  payload jsonb not null,
  version bigint not null default 0
);

-- 7. Row Level Security: Enforce on ALL tables
alter table public.enrolled_users enable row level security;
alter table public.trusted_devices enable row level security;
alter table public.capture_sessions enable row level security;
alter table public.enrollment_requests enable row level security;
alter table public.access_audit_logs enable row level security;
alter table public.vault_records enable row level security;

-- 8. Zero Direct Browser Access: Revoke all from public/anon/authenticated
revoke all on public.enrolled_users, public.trusted_devices, public.capture_sessions,
               public.enrollment_requests, public.access_audit_logs, public.vault_records
from anon, authenticated;

-- Grant least privilege only to service_role (used exclusively by backend server)
grant select, insert, update, delete on public.enrolled_users, public.trusted_devices,
                                       public.capture_sessions, public.enrollment_requests,
                                       public.access_audit_logs, public.vault_records
to service_role;
grant usage, select on all sequences in schema public to service_role;

-- 9. Atomic CAS Commit RPC
create or replace function public.vault_commit(
  record_id text, expected_version bigint, new_payload jsonb,
  audit_event jsonb default null, alert_job jsonb default null
) returns boolean language plpgsql security invoker set search_path = public, pg_temp as $$
declare changed integer;
begin
  if expected_version = -1 then
    insert into public.vault_records(id,payload,version) values(record_id,new_payload,0) on conflict do nothing;
  else
    update public.vault_records set payload=new_payload,version=version+1
      where id=record_id and version=expected_version;
  end if;
  get diagnostics changed = row_count;
  if changed = 0 then return false; end if;

  if audit_event is not null then
    insert into public.access_audit_logs(
      event_id, timestamp, mode, verified_parties, party_ids, verdict, reason,
      reason_code, risk_score, sha256_hash, previous_hash, event_hash,
      signature, signer_key_id, encrypted_path, status, pwa_data
    )
    values(
      (audit_event->>'id')::uuid,
      coalesce((audit_event->>'timestamp')::timestamptz, now()),
      audit_event->>'mode',
      coalesce((audit_event->'parties')::text, '[]'),
      '',
      audit_event->>'verdict',
      coalesce(audit_event->>'reason', ''),
      coalesce(audit_event->>'reason_code', ''),
      coalesce((audit_event->>'risk_score')::integer, 0),
      coalesce(audit_event->>'sha256_hash', ''),
      coalesce(audit_event->>'previous_hash', ''),
      coalesce(audit_event->>'event_hash', ''),
      coalesce(audit_event->>'signature', ''),
      coalesce(audit_event->>'signer_key_id', ''),
      coalesce(audit_event->'evidence'->>'path', ''),
      coalesce(audit_event->>'status', 'CLOUD_STORED'),
      audit_event
    )
    on conflict(event_id) do nothing;
  end if;

  if alert_job is not null then
    insert into public.vault_records(id,payload,version)
      values('job:' || (alert_job->>'id'),alert_job,0) on conflict do nothing;
  end if;
  return true;
end $$;

revoke all on function public.vault_commit(text,bigint,jsonb,jsonb,jsonb) from public,anon,authenticated;
grant execute on function public.vault_commit(text,bigint,jsonb,jsonb,jsonb) to service_role;

-- 10. Private Encrypted Evidence Storage Bucket
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('encrypted-evidence','encrypted-evidence',false,5242880,array['application/octet-stream'])
on conflict(id) do update set public=false,file_size_limit=5242880,allowed_mime_types=array['application/octet-stream'];

-- 11. Web Push Subscriptions Table
create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id text,
  endpoint text unique not null,
  p256dh text not null,
  auth text not null,
  user_agent text,
  device_label text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  enabled boolean not null default true
);

create index if not exists idx_push_subs_user on public.push_subscriptions(user_id);
create index if not exists idx_push_subs_enabled on public.push_subscriptions(enabled);

alter table public.push_subscriptions enable row level security;
revoke all on public.push_subscriptions from anon, authenticated;
grant select, insert, update, delete on public.push_subscriptions to service_role;

commit;
